import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MockApiService, Invoice, User } from '../services/mock-api.service';

@Component({
  selector: 'app-invoices',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="invoices-container p-4">
      <div class="mb-4" *ngIf="currentUser">
        <h2 class="font-display font-bold text-white mb-0">
          {{ currentUser.role === 'fleet-owner' ? 'My Billing Statements' : 'Workshop Earnings & Invoices' }}
        </h2>
        <span class="text-secondary text-sm">
          {{ currentUser.role === 'fleet-owner' ? 'Review invoices, service details, and settle outstanding balances' : 'Monitor parts and labor revenues generated by completed repairs' }}
        </span>
      </div>

      <!-- Overview Cards -->
      <div class="grid-cols-3 mb-4" *ngIf="currentUser">
        <div class="glass-card stat-tile">
          <span class="tile-label">Total Invoiced Amount</span>
          <span class="tile-val mt-1 font-display text-white">₹{{ totalInvoicedSum() | number }}</span>
        </div>
        <div class="glass-card stat-tile">
          <span class="tile-label">Settled (Paid) Invoices</span>
          <span class="tile-val mt-1 font-display text-success">₹{{ settledSum() | number }}</span>
        </div>
        <div class="glass-card stat-tile">
          <span class="tile-label">Outstanding Balances</span>
          <span class="tile-val mt-1 font-display text-danger">₹{{ outstandingSum() | number }}</span>
        </div>
      </div>

      <!-- Invoices Listing -->
      <div class="glass-card">
        <h3 class="text-white text-bold mb-4">Billing Catalog</h3>
        <div class="table-container">
          <table class="custom-table text-left">
            <thead>
              <tr>
                <th>Invoice ID</th>
                <th>Service Center</th>
                <th>Vehicle Details</th>
                <th>Invoice Date</th>
                <th>Total Cost</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let inv of invoices">
                <td class="font-mono text-xs text-muted">{{ inv.id }}</td>
                <td class="text-bold text-white">{{ inv.garageName }}</td>
                <td>{{ inv.vehiclePlate }}</td>
                <td class="font-mono">{{ inv.date }}</td>
                <td class="text-bold text-white">₹{{ inv.amount | number }}</td>
                <td>
                  <span class="badge" [ngClass]="inv.status === 'Paid' ? 'badge-success' : 'badge-danger'">
                    {{ inv.status }}
                  </span>
                </td>
                <td>
                  <button *ngIf="inv.status === 'Unpaid' && currentUser?.role === 'fleet-owner'" class="btn btn-primary btn-xxs" (click)="payInvoice(inv.id)">
                    Pay Invoice
                  </button>
                  <button class="btn btn-secondary btn-xxs" (click)="printInvoice(inv.id)">
                    Print Invoice
                  </button>
                </td>
              </tr>
              <tr *ngIf="invoices.length === 0">
                <td colspan="7" class="text-center py-6 text-muted">No billing statements available.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .invoices-container {
      display: flex;
      flex-direction: column;
      gap: 20px;
    }
    .btn-xxs {
      padding: 4px 8px;
      font-size: 0.7rem;
    }
  `]
})
export class InvoicesComponent implements OnInit {
  currentUser: User | null = null;
  invoices: Invoice[] = [];

  // sums
  totalInvoicedSum = signal(0);
  settledSum = signal(0);
  outstandingSum = signal(0);

  constructor(private mockApi: MockApiService) {}

  ngOnInit() {
    this.mockApi.currentUser$.subscribe(user => {
      this.currentUser = user;
      if (user) {
        this.loadInvoices();
      }
    });
  }

  loadInvoices() {
    if (!this.currentUser) return;

    this.mockApi.getInvoices().subscribe(list => {
      if (this.currentUser?.role === 'fleet-owner') {
        const ownerKey = (this.currentUser?.name || '').split(' ')[0].toLowerCase();
        this.invoices = list.filter(i => i.customerName.toLowerCase().includes(ownerKey));
      } else if (this.currentUser?.role === 'service-center') {
        this.mockApi.getGarages().subscribe(garages => {
          const myGarage = garages.find(g => g.email === this.currentUser?.email);
          if (myGarage) {
            this.invoices = list.filter(i => i.garageName === myGarage.name);
          }
        });
      } else {
        this.invoices = list;
      }

      // calculate sums
      const total = this.invoices.reduce((sum, i) => sum + i.amount, 0);
      const paid = this.invoices.filter(i => i.status === 'Paid').reduce((sum, i) => sum + i.amount, 0);
      const unpaid = this.invoices.filter(i => i.status === 'Unpaid').reduce((sum, i) => sum + i.amount, 0);

      this.totalInvoicedSum.set(total);
      this.settledSum.set(paid);
      this.outstandingSum.set(unpaid);
    });
  }

  payInvoice(id: string) {
    this.mockApi.payInvoice(id).subscribe({
      next: (ok) => {
        if (ok) {
          alert('Payment Successful! Settle reference recorded.');
          this.loadInvoices();
        }
      }
    });
  }

  printInvoice(id: string) {
    alert(`Generating print job spooler for invoice: ${id}`);
  }
}
